#!/usr/bin/env python3
"""Generate docs/normalization_rules.md from tests/normalization/cases.yaml."""

from __future__ import annotations

from pathlib import Path
import textwrap

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CASES_PATH = PROJECT_ROOT / "tests" / "normalization" / "cases.yaml"
DOC_PATH = PROJECT_ROOT / "docs" / "normalization_rules.md"


def _load_cases() -> list[dict]:
    if not CASES_PATH.exists():
        raise FileNotFoundError(f"Missing cases file: {CASES_PATH}")
    data = yaml.safe_load(CASES_PATH.read_text(encoding="utf-8"))
    if not data:
        return []
    if not isinstance(data, list):
        raise ValueError("Normalization cases must be a list of cases.")
    return data


def _format_case(case: dict) -> str:
    rule = case.get("rule", "").strip()
    raw = case.get("input", "")
    expected = case.get("expected", "")
    case_id = case.get("id", "")

    lines = []
    header = f"### {case_id}" if case_id else "### Case"
    lines.append(header)
    if rule:
        lines.append(rule)
    def _escaped(value: str) -> str:
        return value.encode("unicode_escape").decode("ascii")

    if raw is not None:
        lines.append("")
        lines.append("Input (escaped):")
        lines.append("```text")
        lines.append(_escaped(raw))
        lines.append("```")
    if expected is not None:
        lines.append("")
        lines.append("Expected (escaped):")
        lines.append("```text")
        lines.append(_escaped(expected))
        lines.append("```")
    return "\n".join(lines)


def main() -> int:
    cases = _load_cases()
    parts = [
        "# Normalization Rules",
        "",
        "This document is generated from `tests/normalization/cases.yaml`.",
        "Do not edit this file directly.",
        "",
        "## Rules & Examples",
    ]
    for case in cases:
        parts.append("")
        parts.append(_format_case(case))

    DOC_PATH.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")
    print(f"OK: wrote {DOC_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
