#!/usr/bin/env python3
"""Generate docs/normalization_rules.md from tests/normalization/cases.yaml."""

from __future__ import annotations

from pathlib import Path
import textwrap

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CASES_PATH = PROJECT_ROOT / "tests" / "normalization" / "cases.yaml"
DOC_PATH = PROJECT_ROOT / "docs" / "normalization_rules.md"


def _load_cases() -> list[dict]:
    if not CASES_PATH.exists():
        raise FileNotFoundError(f"Missing cases file: {CASES_PATH}")
    data = yaml.safe_load(CASES_PATH.read_text(encoding="utf-8"))
    if not data:
        return []
    if not isinstance(data, list):
        raise ValueError("Normalization cases must be a list of rules.")
    return data


def _format_rule(rule: dict) -> str:
    rule_id = rule.get("id", "")
    rule_text = rule.get("rule", "").strip()
    examples = rule.get("examples", [])

    lines = []
    header = f"### {rule_id}" if rule_id else "### Rule"
    lines.append(header)
    if rule_text:
        lines.append(rule_text)

    def _escaped(value: str) -> str:
        return value.encode("unicode_escape").decode("ascii")

    for idx, example in enumerate(examples, start=1):
        raw = example.get("input", "")
        expected = example.get("expected", "")
        lines.append("")
        lines.append(f"Example {idx}:")
        lines.append("")
        lines.append("Input (escaped):")
        lines.append("```text")
        lines.append(_escaped(raw))
        lines.append("```")
        lines.append("")
        lines.append("Expected (escaped):")
        lines.append("```text")
        lines.append(_escaped(expected))
        lines.append("```")
    return "\n".join(lines)


def main() -> int:
    cases = _load_cases()
    parts = [
        "# Normalization Rules",
        "",
        "This document is generated from `tests/normalization/cases.yaml`.",
        "Do not edit this file directly.",
        "",
        "## Rules & Examples",
    ]
    for rule in cases:
        parts.append("")
        parts.append(_format_rule(rule))

    DOC_PATH.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")
    print(f"OK: wrote {DOC_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
